#!/bin/sh
# -*- mode: shell-script -*-
# -----------------------------------------------------------------
# Tangles the org-mode files and even compresses some.

DIR=$(dirname $0)
FILES=""
     
# wrap each argument in the code required to call tangle on it
for i in $DIR/*.org $DIR/bin/*.org $@; do
    FILES="$FILES \"$i\""
done

/usr/local/bin/emacs -Q --batch \
    --eval "(progn
     (require 'org)(require 'org-exp)(require 'ob)(require 'ob-tangle)
     (mapc (lambda (file)
            (find-file (expand-file-name file \"$DIR\"))
            (org-babel-tangle)
            (kill-buffer)) '($FILES)))" 2>&1 |grep -i tangled

# Set up all the symbolic links:

if [ ! -f $HOME/.vimrc ]
then
    echo "Linking .vimrc ... Don't know why I really care about vi"
    ln -s $DIR/vimrc $HOME/.vimrc
fi

# Especially the .emacs.d directory:

for FILE in emacs.d/*.el
do
    F=$(basename $FILE)
    if [ ! -f $HOME/.emacs.d/elisp/$F ]
    then
        echo "Linking $FILE"
        ln -s $DIR/$FILE $HOME/.emacs.d/elisp
    fi
done
