#+TITLE:  Emacs EMMS
#+AUTHOR: Howard Abrams
#+EMAIL:  howard.abrams@gmail.com
#+DATE:   2014 Jul 24
#+TAGS:   emacs music

This file attempts to define the needs I have for streaming music from
Emacs at work instead of using iTunes like the good lord intended.

* Setup and Installation

  To begin, install all the goodness:

  #+BEGIN_EXAMPLE
  # brew install mpg321
  # brew install mpg123
  brew install mplayer
  #+END_EXAMPLE

  Load up the system and the players. Including configure to show the
  current track each time EMMS starts to play a track.

  #+BEGIN_SRC elisp
    (use-package emms-setup
      :init
      (add-hook 'emms-player-started-hook 'emms-show)
      (setq emms-show-format "Playing: %s")
      :config
      (emms-standard)
      (emms-default-players))
  #+END_SRC

* Radio Stations

  Perhaps the easiest approach is just to have some radio stations
  wrapped up in some easy-to-functions, for instance:

  #+BEGIN_SRC elisp :tangle no
    (defun play-smooth-jazz ()
      "Start up some nice Jazz"
      (interactive)
      (emms-play-streamlist "http://thejazzgroove.com/itunes.pls"))
  #+END_SRC

  And then bind it to some key, however, I’m sure I will start picking
  up a larger and larger collection of radio stations that fit my
  mood, so I might as well create a prefix for these using my snazzy
  dazzy =define-sequence= macro:

  #+BEGIN_SRC elisp
    (define-sequence 'personal-music-map "<f9> m" 'emms-play-streamlist
      '(("a" "http://stereoscenic.com/pls/pill-hi-mp3.pls") ;; Ambient
        ("t" "http://www.1.fm/tunein/trance64k.pls")        ;; Trance
        ("j" "http://thejazzgroove.com/itunes.pls")))       ;; Jazz
  #+END_SRC

* Controlling the Music

  Stopping should be a bit quicker to hit:

  #+BEGIN_SRC elisp
  (define-key personal-music-map (kbd "s") 'emms-stop)
  #+END_SRC

* Technical Artifacts

  Make sure that we can simply =require= this library.

  #+BEGIN_SRC elisp
  (provide 'init-emms)
  #+END_SRC

  Before you can build this on a new system, make sure that you put
  the cursor over any of these properties, and hit: =C-c C-c=

#+DESCRIPTION: A literate programming version of my Emacs Initialization for Graphical Clients

#+PROPERTY:    header-args:sh     :tangle no
#+PROPERTY:    header-args:elisp  :tangle ~/.emacs.d/elisp/init-emms.el
#+PROPERTY:    header-args:       :results silent   :eval no-export   :comments org

#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:nil
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
