#+TITLE:  Emacs Smart Mode Line
#+AUTHOR: Howard Abrams
#+EMAIL:  howard.abrams@gmail.com
#+DATE:   2014 Sep 02
#+TAGS:   emacs

This literate programming file tangles out the configuration for
creating a better mode line in Emacs.

* Smart Mode Line

  While I like the cleanliness of the [[https://github.com/Bruce-Connor/smart-mode-line][Smart Mode Line]], I actually feel
  that I get cleaner mode-lines with [[PowerLine][PowerLine]], so while I'm leaving
  this configuration code here, I'm actually not tangling it.

#+BEGIN_SRC elisp
  (require 'smart-mode-line)
  (if after-init-time (sml/setup)
    (add-hook 'after-init-hook 'sml/setup))

  (custom-set-variables '(sml/active-background-color "dark blue"))
#+END_SRC

    Especially since you can limit the pathname of the displayed
    filename.

#+BEGIN_SRC elisp
  (add-to-list 'sml/replacer-regexp-list '("^~/Google Drive/" ":Goo:"))
  (add-to-list 'sml/replacer-regexp-list '("^~/Google Drive/technical" ":Tech:"))
  (add-to-list 'sml/replacer-regexp-list '("^~/Other/dot-files" ":.:"))
  (add-to-list 'sml/replacer-regexp-list '("^~/Work/wpc-api/server/" ":API:"))
  (add-to-list 'sml/replacer-regexp-list '("^~/Work/wpc-fai/ci/" ":CI:"))
#+END_SRC

    Hiding some Minor modes in the mode line is real swell. This
    leaves the mode-line with only important stuff.

#+BEGIN_SRC elisp
  (setq useless-minor-modes '(" AC"   ;; First must have a space. :-(
                              "GitGutter"
                              "Undo-Tree"
                              "Fly"
                              "ARev"
                              "Abbrev"
                              "Fill"
                              "ColorIds"
                              "FIC"
                              "FlyC.*"))
  (setq sml/hidden-modes (mapconcat 'identity useless-minor-modes "\\| *"))
#+END_SRC

* Technical Artifacts

  Make sure that we can simply =require= this library.

#+BEGIN_SRC elisp
  (provide 'init-mode-line2)
#+END_SRC

  Before you can build this on a new system, make sure that you put
  the cursor over any of these properties, and hit: =C-c C-c=

  *Note:*: We are not using this file. If I want to switch, change the
  =tangle= line below to: =~/.emacs.d/elisp/init-mode-line.el=

#+PROPERTY:    tangle ~/.emacs.d/elisp/init-mode-line2.el
#+DESCRIPTION: A literate programming version of my Emacs ModeLine Initialization
#+PROPERTY:    results silent
#+PROPERTY:    eval no-export
#+PROPERTY:    comments org
#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:nil
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
