#+TITLE:  Blogging with Emacs and org-page
#+AUTHOR: Howard
#+EMAIL:  howard.abrams@gmail.com
#+DATE:   2014 Apr 13
#+TAGS:   emacs blog website

After playing around with [[https://github.com/kelvinh/org-page][org-page]], I've decided to lease it for a
while. Which amounts to doing the following:

#+BEGIN_SRC elisp :tangle no
  (let ((repo "~/Google Drive/howardism-web"))
    (make-directory repo)
    (op/new-repository repo))
#+END_SRC

Of course, we need to make sure that our [[file:~/Work/Personal/gitolite-admin/conf/gitolite.conf::repo%20website-howardism][Git server]] supports this new
repository.

#+BEGIN_SRC elisp
  (when (autofeaturep 'org-page)
    (require 'org-page)

    (setq op/repository-directory "~/Google Drive/howardism-web")
    (setq op/site-main-title "howardisms")
    (setq op/site-sub-title "Slay dragons with Lisp and Philosophy.")

    (setq op/site-domain "http://www.howardism.org/")
    (setq op/personal-github-link "https://github.org/howardabrams")

    ;; The op/template-directory is calculated from the "theme" and the
    ;; 'file-name-as-directory' (which is actually useless, since that
    ;; points into the MELPA directory story. So this should be complete
    ;; overridden.
    ; (setq op/template-directory
    ;      "~/Google Drive/howardism-web-theme/mdo/templates")

    ;;; for commenting, you can choose either disqus or duoshuo
    (setq op/personal-disqus-shortname "howardabrams")
    ;; (setq op/personal-duoshuo-shortname "your_duoshuo_shortname")

    ;;; the configuration below are optional
    ;; (setq op/personal-google-analytics-id "your_google_analytics_id")
  )
#+END_SRC

* Other Variables

  Like most good Emacs packages, =org-page= has a pretty good
  collection of [[https://github.com/kelvinh/org-page/blob/master/op-vars.el][customizable variables]].

* Theme

  The default theme that comes with =org-page= is pretty descent, and
  should be sufficient just to customize the CSS file only. However,
  the =mdo= theme (see the =op/theme= variable) is pulling its
  contents directly from the MELPA downloaded distribution:
  =~/.emacs.d/elpa/org-page-20140330.2032/themes/mdo/=

  I could create my own based on his, and then modify the
  =op/template-directory= which points directly into the themes
  directory.

  In particular, check out the =container.mustache= file which holds
  the basic layout of a page.
* Technical Artifacts

  Before you can build this on a new system, make sure that you put
  the cursor over any of these properties, and hit: =C-c C-c=

#+DESCRIPTION: Instructions for getting Emacs to be able to publish a blog system using org-page
#+PROPERTY:    results silent
#+PROPERTY:    tangle ~/.emacs.d/elisp/init-blog.el
#+PROPERTY:    eval no-export
#+PROPERTY:    comments org
#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:nil
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
