#+TITLE:  Emacs Initialization for ElFeed
#+AUTHOR: Howard Abrams
#+EMAIL:  howard.abrams@gmail.com
#+DATE:   2014 Jul 21
#+TAGS:   emacs

Going to play around with [[https://github.com/skeeto/elfeed][ElFeed]] to see about reading a small
collection of articles in Emacs (see [[http://nullprogram.com/blog/2013/09/04/][this introduction]]).
Let's load it up if it is installed.

#+BEGIN_SRC elisp
  (use-package elfeed
    :ensure   t
    :commands elfeed
    :init     (define-key personal-global-map (kbd "r") 'elfeed))
#+END_SRC

* The Feeds

  We just need to maintain a list of the RSS and Atom feeds we want to
  read. Personally, I don't want a lot of /entries/. No
  /announcements/ either...just quality essays. That said,
  Emacs-related essays would be fun to read in Emacs, since any code
  would be trivial to evaluate. ;-)

#+BEGIN_SRC elisp
  (setq elfeed-feeds
        '("http://www.howardism.org/index.xml"     ;; My Blog
          "http://planet.emacsen.org/atom.xml"     ;; Emacs RSS
          "http://sachachua.com/blog/category/emacs-news/feed"
          "http://endlessparentheses.com/atom.xml" ;; Emacs Blog
          "http://www.masteringemacs.org/feed/"    ;; Emacs Blog
          "http://emacs-fu.blogspot.com/feeds/posts/default"
          "http://emacsredux.com/atom.xml"         ;; Emacs Blog
          "http://www.lunaryorn.com/feed.atom"     ;; Emacs Blog
          "http://emacshorrors.com/feed.atom"
          "http://swannodette.github.com/atom.xml" ;; David Nolen, duh.
          "http://batsov.com/atom.xml"             ;; Bozhidar Batsov

          "https://apod.nasa.gov/apod.rss"         ;; Nasa's Picture of the Day
          "http://twogreenleaves.org/index.php?feed=rss"

          "https://medium.com/feed/@hlship/"       ;; Programming
          "http://gigasquidsoftware.com/atom.xml"  ;; Clojure
          "http://blog.fogus.me/feed/"      ;; Programming
          "http://steve-yegge.blogspot.com/atom.xml"
          "http://www.rkn.io/feed.xml"))    ;; Programming
#+END_SRC

  *Note:* I plan on updating my feed list somewhat organically, so
   that I don't get overwhelmed with too much information.

* Tagging and Filtering

  Tag filters start with + and -. When +, entries must be tagged
  with that tag. When -, entries must not be tagged with that tag. Some
  examples,

    +unread: show only unread posts.
    -junk +unread: don't show unread "junk" entries.

  This means, that I would like to not just mark things dynamically, but
  automatically tag certain feeds that I know belong to certain content.

* Technical Artifacts

  Make sure that we can simply =require= this library.

#+BEGIN_SRC elisp
  (provide 'init-elfeed)
#+END_SRC

  Before you can build this on a new system, make sure that you put
  the cursor over any of these properties, and hit: =C-c C-c=

#+DESCRIPTION: A literate programming version of my Emacs Initialization for Graphical Clients

#+PROPERTY:    header-args:sh     :tangle no
#+PROPERTY:    header-args:elisp  :tangle ~/.emacs.d/elisp/init-elfeed.el
#+PROPERTY:    header-args:       :results silent   :eval no-export   :comments org

#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:nil
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
