#+TITLE:  IRC Settings for Emacs
#+AUTHOR: Howard Abrams
#+EMAIL:  howard.abrams@gmail.com
#+DATE:   2014 Mar 28
#+TAGS:   emacs

I'm digging on the [[https://github.com/jorgenschaefer/circe/wiki][Circe]] as my IRC client of choice. Just have to
install it's package:

#+BEGIN_SRC elisp
  (packages-install '(circe))

  (require 'circe)
#+END_SRC

Which means we can create my connections to my servers:

#+BEGIN_SRC elisp
  (add-to-list 'circe-network-options
        '("Ciphermonkeys"
           :host "irc.ciphermonkeys.org"
           :nick "ha"
           :channels ("#1101")))

  (add-to-list 'circe-network-options
        '("Freenode"
          :nick "howardabrams"
          :channels ("#emacs" "#clojure-pdx")
          :nickserv-password ,freenode-password)
          )

  (defun circe-connect-all ()
    "Connects to my favorite IRC servers and channels."
    (interactive)
    (circe "Ciphermonkeys")
    (circe "Freenode"))
#+END_SRC

   Simplify the channel output.

#+BEGIN_SRC elisp
  (setq circe-format-say "{nick}> {body}")
#+END_SRC

   Let's hide all the JOIN, PART and other messages that I don't care
   about:

#+BEGIN_SRC elisp
  (circe-set-display-handler "JOIN" (lambda (&rest ignored) nil))
  (circe-set-display-handler "PART" (lambda (&rest ignored) nil))
  (circe-set-display-handler "QUIT" (lambda (&rest ignored) nil))

  (setq circe-reduce-lurker-spam t)
#+END_SRC

   Circe (actually, lui) has the ability to intercept long pastes if
   it is done in a single input. Lui will then ask if the user would
   prefer to use a paste service.

#+BEGIN_SRC elisp
  (require 'lui-autopaste)
  (add-hook 'circe-channel-mode-hook 'enable-lui-autopaste)
#+END_SRC

   Who can really spell, amirite?

#+BEGIN_SRC elisp
  (setq lui-flyspell-p t
        lui-flyspell-alist '((".*" "american")))
#+END_SRC

   Since I often run my IRC in a smaller window, I need to allow for
   the timestamps to be in a margin, so that we can wrap correctly.

#+BEGIN_SRC elisp
  (setq lui-time-stamp-position 'right-margin
        lui-time-stamp-format "%H:%M")

  (add-hook 'lui-mode-hook 'my-circe-set-margin)
  (defun my-circe-set-margin ()
    (setq right-margin-width 5))

  (setq lui-time-stamp-position 'right-margin
        lui-fill-type nil)

  (add-hook 'lui-mode-hook 'my-lui-setup)
  (defun my-lui-setup ()
    (setq
     fringes-outside-margins t
     right-margin-width 5
     word-wrap t
     wrap-prefix "    "))
#+END_SRC

* Technical Artifacts

  Make sure that we can simply =require= this library.

#+BEGIN_SRC elisp
  (provide 'init-irc)
#+END_SRC

  Before you can build this on a new system, make sure that you put
  the cursor over any of these properties, and hit: =C-c C-c=

#+DESCRIPTION: A literate programming version of my Emacs Initialization for Connecting to IRC
#+PROPERTY:    results silent
#+PROPERTY:    tangle ~/.emacs.d/elisp/init-irc.el
#+PROPERTY:    header-args:sh  :tangle no
#+PROPERTY:    eval no-export
#+PROPERTY:    comments org
#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:nil
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
