#+TITLE:  Emacs Org-Mode Settings
#+AUTHOR: Howard Abrams
#+EMAIL:  howard.abrams@gmail.com
#+DATE:   [2014-02-01 Sat][2014-02-01 Sat]
#+TAGS:   emacs

The [[http://orgmode.org][Org Mode]] feature was a big reason in my recent re-kindling of my
Emacs love affair. Make sure the latest packages are installed:

#+BEGIN_SRC elisp
  (packages-install '( org
                       org-mime
                       ox-reveal
                       org-journal
                       plantuml-mode
                     ))
#+END_SRC

* Initial Settings

  I really think that org-mode should be my default for most things,
  including regular text files:

#+BEGIN_SRC elisp
  (add-to-list 'auto-mode-alist '("\\.txt\\'" . org-mode))
#+END_SRC

   Initialization of Org Mode by hooking it into YASnippets, which
   should allow me to easily add templates to my files.

#+BEGIN_SRC elisp
  (add-hook 'org-mode-hook
            '(lambda ()
               (yas/minor-mode-on)))
#+END_SRC

* Journaling

   Didn't realize that [[http://www.emacswiki.org/emacs/OrgJournal][org-journal]] essentially does what I have been
   doing by hand. With a little customization, I don't have to change
   anything else:

#+BEGIN_SRC elisp
  (setq org-journal-dir "~/journal/")

  (when (autofeaturep 'org-journal)
        (require 'org-journal))
#+END_SRC

   All my journal entries will be formatted using org-mode:

#+BEGIN_SRC elisp
  (add-to-list 'auto-mode-alist '(".*/[0-9]*$" . org-mode))
#+END_SRC

   The date format is essentially, the top of the file.

#+BEGIN_SRC elisp
  (setq org-journal-date-format "#+TITLE: Journal Entry- %Y-%b-%d (%A)")
#+END_SRC

   The time format is the heading for each section. I will set it to a
   blank since I really don't care about the time I add a section.

#+BEGIN_SRC elisp
  (setq org-journal-time-format "")
#+END_SRC

    A function to easily load today (and yesterday's) journal entry.

#+BEGIN_SRC elisp
  (defun get-journal-file-today ()
    "Return filename for today's journal entry."
    (let ((daily-name (format-time-string "%Y%m%d")))
      (expand-file-name (concat org-journal-dir daily-name))))

  (defun journal-file-today ()
    "Create and load a journal file based on today's date."
    (interactive)
    (find-file (get-journal-file-today)))

  (global-set-key (kbd "C-c f j") 'journal-file-today)
#+END_SRC

    Since I sometimes (not often) forget to create a journal entry,
    and need to re-write history.

#+BEGIN_SRC elisp
    (defun get-journal-file-yesterday ()
      "Return filename for yesterday's journal entry."
      (let ((daily-name (format-time-string "%Y%m%d" (time-subtract (current-time) (days-to-time 1)))))
        (expand-file-name (concat org-journal-dir daily-name))))

    (defun journal-file-yesterday ()
      "Creates and load a file based on yesterday's date."
      (interactive)
      (find-file (get-journal-file-yesterday)))

    (global-set-key (kbd "C-c f y") 'journal-file-yesterday)
#+END_SRC

    Seems like I need to have the inserted template match the file's
    name, not necessarily today's date:

  #+BEGIN_SRC elisp
    (defun journal-file-insert ()
      "Insert's the journal heading based on the file's name."
      (interactive)
      (when (string-match "\\(20[0-9][0-9]\\)\\([0-9][0-9]\\)\\([0-9][0-9]\\)" (buffer-name))
        (let ((year  (string-to-number (match-string 1 (buffer-name))))
              (month (string-to-number (match-string 2 (buffer-name))))
              (day   (string-to-number (match-string 3 (buffer-name))))
              (datim nil))
          (setq datim (encode-time 0 0 0 day month year))
          (insert (format-time-string org-journal-date-format datim))
          (insert "\n\n"))))  ; Start with a blank separating line
  #+END_SRC

    Nice to /automatically/ insert this header if the journal entry
    file is empty...yeah, we're talking [[https://www.gnu.org/software/emacs/manual/html_node/autotype/Autoinserting.html][auto-insert]]:

  #+BEGIN_SRC elisp
    (add-to-list 'auto-insert-alist '(".*/[0-9]*$" . journal-file-insert))
  #+END_SRC

    I really would really like to read what I did last year "at this
    time", and by that, I mean, 365 days ago, plus or minus a few to get
    to the same day of the week.

#+BEGIN_SRC elisp
  (defun journal-last-year-file ()
    "Returns the string corresponding to the journal entry that
  happened 'last year' at this same time (meaning on the same day
  of the week)."
  (let* ((last-year-seconds (- (float-time) (* 365 24 60 60)))
         (last-year (seconds-to-time last-year-seconds))
         (last-year-dow (nth 6 (decode-time last-year)))
         (this-year-dow (nth 6 (decode-time)))
         (difference (if (> this-year-dow last-year-dow)
                         (- this-year-dow last-year-dow)
                       (- last-year-dow this-year-dow)))
         (target-date-seconds (+ last-year-seconds (* difference 24 60 60)))
         (target-date (seconds-to-time target-date-seconds)))
    (format-time-string "%Y%m%d" target-date)))

  (defun journal-last-year ()
    "Loads last year's journal entry, which is not necessary the
  same day of the month, but will be the same day of the week."
    (interactive)
    (let ((journal-file (concat org-journal-dir (journal-last-year-file))))
      (find-file journal-file)))

    (global-set-key (kbd "C-c f L") 'journal-last-year)
  #+END_SRC

** Taking Meeting Notes

    I've notice that while I really like taking notes in a meeting, I
    don't always like the multiple windows I have opened, so I created
    this function that I can easily call to eliminate distractions
    during a meeting.

#+BEGIN_SRC elisp
(defun meeting-notes ()
  "Call this after creating an org-mode heading for where the notes for the meeting
should be. After calling this function, call 'meeting-done' to reset the environment."
  (interactive)
  (outline-mark-subtree)                              ;; Select org-mode section
  (narrow-to-region (region-beginning) (region-end))  ;; Only show that region
  (deactivate-mark)
  (delete-other-windows)                              ;; Get rid of other windows
  (text-scale-set 2)                                  ;; Text is now readable by others
  (global-set-key (kbd "<f6>") 'meeting-done)
  (message "When finished taking your notes, press <F6>"))
#+END_SRC

    Of course, I need an 'undo' feature when the meeting is over...

#+BEGIN_SRC elisp
(defun meeting-done ()
  "Attempt to 'undo' the effects of taking meeting notes."
  (interactive)
  (widen)                                       ;; Opposite of narrow-to-region
  (text-scale-set 0)                            ;; Reset the font size increase
  (winner-undo))                                ;; Put the windows back in place
#+END_SRC

** Org-Mode Colors

  Before we load =org-mode= proper, we need to set the following
  syntax high-lighting parameters. These are used to help bring out
  the source code during literate programming mode.

  This information came from [[http://orgmode.org/worg/org-contrib/babel/examples/fontify-src-code-blocks.html][these instructions]], however, they tend
  to conflict with the /color-theme/, so we'll turn them off for now.

#+BEGIN_SRC elisp
  (defface org-block-begin-line
    '((t (:underline "#A7A6AA" :foreground "#008ED1" :background "#EAEAFF")))
    "Face used for the line delimiting the begin of source blocks.")

  (defface org-block-background
    '((t (:background "#FFFFEA")))
    "Face used for the source block background.")

  (defface org-block-end-line
    '((t (:overline "#A7A6AA" :foreground "#008ED1" :background "#EAEAFF")))
    "Face used for the line delimiting the end of source blocks.")
#+END_SRC

* Library Loading

   The standard package manager (and most recent versions of Emacs)
   include =org-mode=, however, I want the latest version that has
   specific features for literate programming.

   Org-mode is installed in the global directory.

#+BEGIN_SRC elisp
  (require 'org)
  (require 'ob-tangle)
#+END_SRC

* Global Key Bindings

   The =org-mode= has some useful keybindings that are helpful no
   matter what mode you are using currently.

#+BEGIN_SRC elisp
  (global-set-key (kbd "C-c l") 'org-store-link)
  (global-set-key (kbd "C-c a") 'org-agenda)
  (global-set-key (kbd "C-c b") 'org-iswitchb)

  (global-set-key (kbd "C-M-|") 'indent-rigidly)
#+END_SRC

* Local Key Bindings

  The following keybind ideas came from [[http://eschulte.github.io/emacs24-starter-kit/starter-kit-org.html][Emacs24 Starter Kit]].

#+BEGIN_SRC elisp
(add-hook 'org-mode-hook
          (lambda ()
            (local-set-key "\M-\C-n" 'outline-next-visible-heading)
            (local-set-key "\M-\C-p" 'outline-previous-visible-heading)
            (local-set-key "\M-\C-u" 'outline-up-heading)
            ;; table
            (local-set-key "\M-\C-w" 'org-table-copy-region)
            (local-set-key "\M-\C-y" 'org-table-paste-rectangle)
            (local-set-key "\M-\C-l" 'org-table-sort-lines)
            ;; display images
            (local-set-key "\M-I" 'org-toggle-iimage-in-org)))
#+END_SRC

   A couple of short-cut keys to make it easier to edit text.

#+BEGIN_SRC elisp
  (defun org-text-bold () "Wraps the region with asterisks."
    (interactive)
    (surround-text "*"))
  (defun org-text-italics () "Wraps the region with slashes."
    (interactive)
    (surround-text "/"))
  (defun org-text-code () "Wraps the region with equal signs."
    (interactive)
    (surround-text "="))
#+END_SRC

   Now we can associate some keystrokes to the org-mode:

#+BEGIN_SRC elisp
  (add-hook 'org-mode-hook
        (lambda ()
          (local-set-key (kbd "A-b") 'org-text-bold)
          (local-set-key (kbd "s-b") 'org-text-bold)    ;; For Linux
          (local-set-key (kbd "A-i") 'org-text-italics)
          (local-set-key (kbd "s-i") 'org-text-italics)
          (local-set-key (kbd "A-=") 'org-text-code)
          (local-set-key (kbd "s-=") 'org-text-code)))
#+END_SRC

   When pasting certain kinds of links, the "text" may be obvious.

#+BEGIN_SRC elisp
  (defun org-generate-link-description (url description)
    (cond
     ((string-match "jira.workday" url)
      (replace-regexp-in-string "https://jira.+/browse/" "" url))
     ((string-match "crucible.workday" url)
      (replace-regexp-in-string "https://crucible.+/cru/" "" url))
     (t description)))

  (setq org-make-link-description-function 'org-generate-link-description)
#+END_SRC

   I'm often typing Jira entries that match a particular link pattern.

#+BEGIN_SRC elisp
  (defun jira-link (b e)
    "Wraps the region with an org-mode link."
    (interactive "r")
    (save-restriction
      (narrow-to-region b e)
      (let ((jiraid (buffer-substring (point-min) (point-max))))
        (goto-char (point-min))
        (insert "[[https://jira.workday.com/browse/" jiraid "][")
        (goto-char (point-max))
        (insert "]]"))))
#+END_SRC

* Speed Keys

   If point is at the beginning of a headline or code block in
   org-mode, single keys do fun things. See =org-speed-command-help=
   for details (or hit the ? key at a headline).

#+BEGIN_SRC elisp
  (setq org-use-speed-commands t)
#+END_SRC

* Specify the Org Directories

   I keep all my =org-mode= files in a few directories, and I would
   like them automatically searched when I generate agendas.

#+BEGIN_SRC elisp
(setq org-agenda-files '("~/Dropbox/org/personal"
                         "~/Dropbox/org/technical"
                         "~/Dropbox/org/project"))
#+END_SRC

* Auto Note Capturing

   Let's say you were in the middle of something, but would like to
   /take a quick note/, but without affecting the file you are
   working on. This is called a "capture", and is bound to the
   following key:

#+BEGIN_SRC elisp
  (global-set-key (kbd "C-c c") 'org-capture)
#+END_SRC

   This will bring up a list of /note capturing templates/. I actually
   have this information stored in my [[file:emacs-local.org::*Org%20Configuration][system-specific "local" configuration]]
   file.

#+BEGIN_SRC elisp :tangle no
  (defun ha/first-header ()
      (goto-char (point-min))
      (search-forward-regexp "^\* ")
      (beginning-of-line 1)
      (point))

  (setq org-capture-templates
        '(("n" "Thought or Note"  entry (file "~/personal/@SUMMARY.org")
           "* %?\n\n  %i\n\n  See: %a" :empty-lines 1)
          ("j" "Journal Note"     entry (file (get-journal-file-today))
           "* %?\n\n  %i\n\n  From: %a" :empty-lines 1)
          ("w" "Website Announcement" entry
           (file+function "~/website/index.org" ha/first-header)
           "* %?
    :PROPERTIES:
    :PUBDATE: %t
    :END:
    #+HTML: <div class=\"date\">%<%e %b %Y></div>

    %i

    [[%F][Read more...]]" :empty-lines 1)))

  ;; General notes go into this file:
  (setq org-default-notes-file "~/personal/@SUMMARY.org")
#+END_SRC

   After you have selected the template, you type in your note and hit
   =C-c C-c= to store it in the file listed above.

   Just remember, at some point to hit =C-c C-w= to /refile/ that note
   in the appropriate place.

* Checking Things Off

   When I check off an item as done, sometimes I want to add some
   details about the completion (this is really only helpful when I'm
   consulting).

   With this setting, each time you turn an entry from a TODO state
   into the DONE state, a line 'CLOSED: [timestamp]' will be inserted
   just after the headline. If you turn the entry back into a TODO
   item through further state cycling, that line will be removed
   again.

#+BEGIN_SRC elisp
  ; (setq org-log-done 'time)
  (setq org-log-done 'note)
#+END_SRC

* Export Settings

    To make the =org-mode= export defaults closer to my liking
    (without having to put specific #+PROPERTY commands), start by
    =describe-variable= the =org-export-plist-vars= variable.

    This returns the list of variables that can be customized:

#+BEGIN_SRC elisp
  (setq org-export-with-section-numbers nil)
  (setq org-export-with-toc nil)
  (setq org-export-skip-text-before-1st-heading nil)

  (setq org-export-html-postamble nil) ;; don't need any gunk at end

  (setq org-export-creator-info nil)
  (setq org-export-email-info nil)
  (setq org-export-author-info nil)
  (setq org-export-time-stamp-file nil)
  (setq org-export-html-with-timestamp nil)
#+END_SRC

* Narrowing and Widening

  After reading [[http://endlessparentheses.com/emacs-narrow-or-widen-dwim.html][this article]], I decided to expand how I narrow/widen
  buffer sections in org-mode. This is specific to org-mode, as I
  often like to see the surrounding code using =fancy-narrow= as
  explained in my [[file:emacs.org::*Expand%20Region][Expand Region]] section.

  #+BEGIN_SRC elisp
    (defun org-narrow-or-widen-dwim (p)
      "If the buffer is narrowed, it widens. Otherwise, it narrows intelligently.
    Intelligently means: region, org-src-block, org-subtree, or defun,
    whichever applies first.
    Narrowing to org-src-block actually calls `org-edit-src-code'.

    With prefix P, don't widen, just narrow even if buffer is already
    narrowed."
      (interactive "P")
      (declare (interactive-only))
      (cond ((and (buffer-narrowed-p) (not p)) (widen))
            ((region-active-p)
             (narrow-to-region (region-beginning) (region-end)))
            ((derived-mode-p 'org-mode)
             (cond ((ignore-errors (org-edit-src-code))
                    (delete-other-windows))
                   ((org-at-block-p)
                    (org-narrow-to-block))
                   (t (org-narrow-to-subtree))))
            (t (narrow-to-defun))))

    (global-set-key (kbd "C-x n o") 'org-narrow-or-widen-dwim)
  #+END_SRC

    According to [[http://endlessparentheses.com/emacs-narrow-or-widen-dwim.html][the narrow-widen article]], we can have =C-x C-s= get
    out of editing org-mode source code blocks:

    #+BEGIN_SRC elisp
      (eval-after-load 'org-src
        '(define-key org-src-mode-map
           "\C-x\C-s" #'org-edit-src-exit))
    #+END_SRC


* Presentations

   Currently generating presentations from my org-mode files using
   [[https://github.com/hakimel/reveal.js/][reveal.js]] and [[https://github.com/yjwen/org-reveal][org-reveal]].

#+BEGIN_SRC elisp
  (when (autofeaturep 'ox-reveal)
    (require 'ox-reveal)

    (setq org-reveal-root (concat "file://" (getenv "HOME") "/Other/reveal.js"))

    (setq org-reveal-postamble "Howard Abrams"))
#+END_SRC

   Displaying the headers using various bullets are nice for my presentations.

#+BEGIN_SRC elisp
  (when (autofeaturep 'org-bullets)
    (require 'org-bullets)
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC

* MobileOrg

   I use [[http://mobileorg.ncogni.to/doc/getting-started/using-dropbox/][Dropbox with MobileOrg]] in order to read my notes on my iPad.

   The "global" location of my Org files on my local system:

#+BEGIN_SRC elisp
  (setq org-directory "~/Dropbox/org/personal")
#+END_SRC

   Set the name of the file where new notes will be stored

#+BEGIN_SRC elisp
  (setq org-mobile-inbox-for-pull "~/Dropbox/org/flagged.org")
#+END_SRC

   Set to <your Dropbox root directory>/MobileOrg.

#+BEGIN_SRC elisp
  (setq org-mobile-directory "~/Dropbox/Apps/MobileOrg")
#+END_SRC

   To get this going, we just need to: =M-x org-mobile-push=

* The Tower of Babel

   The trick to literate programming is in the [[http://orgmode.org/worg/org-contrib/babel/intro.html][Babel project]], which
   allows org-mode to not only interpret source code blocks, but
   evaluate them and tangle them out to a file.

#+BEGIN_SRC elisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((sh         . t)
   (js         . t)
   (emacs-lisp . t)
   (perl       . t)
   (scala      . t)
   (clojure    . t)
   (python     . t)
   (dot        . t)
   (css        . t)
   (plantuml   . t)))
#+END_SRC

   I want CoffeeScript to be supported in org-mode, but I need to do
   it myself at the moment.

#+BEGIN_SRC elisp
  (when (locate-library "ob-coffee")
      (require 'ob-coffee))
#+END_SRC

   It seems to automatically recognize the language used in a source
   block, but if not, call =org-babel-lob-ingest= to add all the
   languages from the code block into the list that Babel supports.
   Keystroke: =C-c C-v i=.

** Just Evaluate It

    I'm normally fine with having my code automatically evaluated.

#+BEGIN_SRC elisp
  (setq org-confirm-babel-evaluate nil)
#+END_SRC

** Font Coloring in Code Blocks

#+BEGIN_SRC elisp
   ; (setq org-src-fontify-natively t)
   (setq org-src-tab-acts-natively t)

   (global-set-key (kbd "<f9> S-f") 'org-src-fontify-buffer)
   (global-set-key (kbd "<f9> f") 'org-src-fontify-block)
#+END_SRC

    Normally, fontifying the individual code blocks makes it
    impossible to work with, so instead of turning it on at the global
    level for all blocks, I created a couple of keystrokes to
    selectively colorize one block at a time.

* Technical Artifacts

  Need to provide the =init-org-mode= so that I can require this
  package.

#+BEGIN_SRC elisp
  (provide 'init-org-mode)
#+END_SRC

  Before you can build this on a new system, make sure that you put
  the cursor over any of these properties, and hit: =C-c C-c=

#+DESCRIPTION: A literate programming version of my Emacs Initialization of Org-Mode
#+PROPERTY:    results silent
#+PROPERTY:    tangle ~/.emacs.d/elisp/init-org-mode.el
#+PROPERTY:    eval no-export
#+PROPERTY:    comments org
#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:nil
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
