#+TITLE:  Shell Dot Profile
#+AUTHOR: Howard Abrams
#+EMAIL:  howard.abrams@gmail.com
#+DATE:   [2013-12-06 Fri]
#+TAGS:   zsh shell

This generates my =.profile= that contains environment variables and
similar settings applicable to all my shells. Yeah, I'm some-what of
a shell-slut, and dabble between Zshell and Fish.

* Homebrew

  Make sure that [[http://brew.sh/][Homebrew]] is both installed and configured correctly.

  #+BEGIN_SRC shell
  if which osascript >/dev/null 2>&1
  then
    export ON_A_MAC=1
  fi

  if [ ! -d /usr/local/Cellar -a -n "$ON_A_MAC" ]
  then
    echo "ZOMG! No Homebrew installed! Installing now..."
    echo 'ruby -e "`curl -fsSL https://raw.github.com/mxcl/homebrew/go/install`"'
  fi
  #+END_SRC

* Path

   We want to add these directories, but only if they exist. This
   makes this more portable between my computers.

   #+BEGIN_SRC shell
     OLDPATH=$PATH
     PATH=$HOME/bin

     for DIR in /opt/local/bin /opt/local/sbin /usr/local/bin /usr/local/sbin
     do
       if [ -d $DIR ]
       then
           PATH=$PATH:$DIR
       fi
     done

     PATH=$PATH:$OLDPATH
   #+END_SRC

* Emacs

  Set =EDITOR= to start up an =emacsclient=, but do that from the one
  I built from Homebrew:

  #+BEGIN_SRC shell
  export ALTERNATE_EDITOR=/usr/local/bin/emacs
  export EDITOR=/usr/local/bin/emacsclient
  #+END_SRC

* Global Aliases

  Just standard things that I keep typing:

  #+BEGIN_SRC shell
    alias e='emacsclient -nw'
    alias ee='emacsclient'
    alias gst='git status'

    if type gls >/dev/null 2>&1
    then
        alias ls='gls --color'
        alias ll='gls -al --color'
    else
        alias ll='ls -al'
    fi
  #+END_SRC

* Python

  Use Homebrew to install the [[https://github.com/yyuu/pyenv][pyenv]] project:

  #+BEGIN_SRC shell :tangle no
    brew install pyenv
  #+END_SRC

  Initialize the project with the following code:

  #+BEGIN_SRC shell
    export PYENV_ROOT="${HOME}/.pyenv"

    if [ -d "${PYENV_ROOT}" ]; then
        export PATH="${PYENV_ROOT}/bin:${PATH}"
        eval "$(pyenv init -)"
    fi
  #+END_SRC

  Install a particular version of Python:

  #+BEGIN_SRC shell :tangle no
    pyenv install 2.7.5
    pyenv global 2.7.5
  #+END_SRC

  Use a particular Python version with:

  #+BEGIN_SRC shell :tangle no
    pyenv virtualenv $NAME    # Creates the virtual env
    pyenv activate $NAME      # Choose the virtual env
    pyenv deactivate          # Stops using it
  #+END_SRC

  While in the root directory of a /project/, automatically use the
  appropriate Python version with the =local= command (do this just
  once):

  #+BEGIN_SRC shell :tangle no
    pyenv local <virtualenv or version>
  #+END_SRC

  When entering this directory, the chosen virtualenv or Python
  version will be activated automatically. The file that is creatied
  and specifies the appropriate environment is named =.python-version=
  (add this to git).

  Enhance =pyenv= with the [[https://github.com/yyuu/pyenv-virtualenv][pyenv-virtualenv]] plugin. If installed, this
  code initializes it:

  #+BEGIN_SRC shell
    if which pyenv-virtualenv-init > /dev/null
    then
        eval "$(pyenv virtualenv-init -)"
    fi
  #+END_SRC

  Create a virtual environment with:

  #+BEGIN_SRC shell :tangle no
    pyenv virtualenv 2.7.10 lp-demo
  #+END_SRC

  List the created virtual environments:

  #+BEGIN_SRC shell :tangle no
    pyenv virtualenvs
  #+END_SRC

  It seems that the =local= command may make this a moot point,
  activate a virtual environment manually with:

  #+BEGIN_SRC shell :tangle no
    pyenv activate <name>
    pyenv deactivate
  #+END_SRC

  In other words, this =pyenv= project subsumes both [[https://github.com/kennethreitz/autoenv][autoenv]] and
  [[http://virtualenvwrapper.readthedocs.org/en/latest/index.html][virtualenvwrapper]]. See [[file:emacs-python.org::*Virtual%20Environments][Virtual Environments]] in the Python Emacs
  setup for details.

  I like the prompt changing feature that will be removed from some
  future release. Let's turn it on.

  #+BEGIN_SRC shell
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
  #+END_SRC

  Completion for =pip= comes from the command: =pip completion --bash=:
  #+BEGIN_SRC shell
    _pip_completion()
    {
        COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
                       COMP_CWORD=$COMP_CWORD \
                       PIP_AUTO_COMPLETE=1 $1 ) )
    }
    complete -o default -F _pip_completion pip
  #+END_SRC

* Ruby

  Install [[https://rvm.io/][RVM]] via:

  #+BEGIN_SRC shell :tangle no
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    curl -sSL https://get.rvm.io | bash -s stable
  #+END_SRC

  And then just source the following:

  #+BEGIN_SRC shell
    source $HOME/.rvm/scripts/rvm
  #+END_SRC

  Create new virtual environments with:

  #+BEGIN_SRC shell :tangle no
    rvm install 2.0.0
    rvm use ruby-2.0.0-p643
    rvm gemset create chef
    rvm gemset use chef
  #+END_SRC

  And use those environements with:

  #+BEGIN_SRC shell :tangle no
    rvm use ruby-2.0.0-p643@chef
  #+END_SRC

  And now =gem= commands work as expected:

  #+BEGIN_SRC shell :tangle no
    gem install bundler
  #+END_SRC

  RVM can give /completion/ capabilities to Bash:
  #+BEGIN_SRC shell
  [[ -r $rvm_path/scripts/completion ]] && . $rvm_path/scripts/completion
  #+END_SRC

* Completions

  Assuming the location of all the Bash completions:

  #+BEGIN_SRC shell
    source /usr/local/etc/bash_completion.d/brew
    # source /usr/local/etc/bash_completion.d/coreutils
    # source /usr/local/etc/bash_completion.d/findutils
    source /usr/local/etc/bash_completion.d/git-prompt.sh
    source /usr/local/etc/bash_completion.d/git-completion.bash
    # source /usr/local/etc/bash_completion.d/ssh
  #+END_SRC

* Prompt

  A helper function to help trim down lengthy directories:

  #+BEGIN_SRC shell
    function _trim_dir {
        V='[[:alnum:]._-]'
        D='[[:alnum:]._/-]'
        sed -E "s|/$D+/($V+)|../\1|; s/ / /g" <<< $1
    }
  #+END_SRC

  The =__git_ps1= is nice, but can be lengthy when pulling down Gerrit
  reviews, so let's make a simpler branch:

  #+BEGIN_SRC shell
    function _mygit_ps1 {
      __git_ps1 " :%s" | sed 's|^ :review/.*/\([0-9]*\)$| :review-\1|'
    }
  #+END_SRC

  Better approach to displaying the current path, is to only display
  the first or second directory name ... any maybe the name of the Git
  project. Holy hell, so many exceptions and so few patterns...

  #+BEGIN_SRC shell
    function prompt_dir {
        PWD=$(pwd)

        if [[ $PWD == $HOME ]]
        then
            echo -n '~'
        elif [[ $PWD == $HOME/Work ]]
        then
            echo -n '~/Work'

             # In a Git project?
        elif PRJ=$(git rev-parse --show-toplevel 2>/dev/null)
        then
            name=$(basename $PRJ)
            rest=$(sed "s|$PRJ||" <<< $PWD)
            echo -n "$(sed -e 's/ / /g' <<< [$name])$(_trim_dir $rest)"

             # In work-related directory...
        elif [[ $PWD == $HOME/Work/* ]]
        then
            name=$(sed -E "s|$HOME/Work/([[:alnum:]_-]+).*|\1|; s/ / /g" <<< $PWD)
            base=$(basename $PWD)
            intr=$(basename "`dirname \"$PWD\"`")

            if [[ "$name" == "$base" ]]
            then
                echo -n "Ⓦ/$name"
            elif [[ "$intr" == "$name" ]]
            then
                echo -n "Ⓦ/$name/$base"
            else
                echo -n "Ⓦ/$name/../$base"
            fi

             # In a home directory
        elif [[ $PWD == $HOME/* ]]
        then
            base=$(basename $PWD)
            intr=$(basename "`dirname \"$PWD\"`")
            if [[ "$intr" == $(basename $HOME) ]]
            then
                echo -n "~/$base"
            else
                echo -n "~/$(_trim_dir $PWD)"
            fi
        else
            _trim_dir $PWD
        fi
    }
  #+END_SRC

  I wanna add everything to my command line prompt: the Git
  repository, the Python virtual environment (in white), the Ruby
  Virtual Environment (in red) ... of course, now I have no room to
  type commands. ;-)

  #+BEGIN_SRC shell
    export PS1='\[\e[1;34m\]$(prompt_dir)\[\e[1;32m\]$(_mygit_ps1)\[\e[0m\] \$ '

    if [ -d ~/.rvm ]
    then
        export PS1='\[\e[1;31m\]$(~/.rvm/bin/rvm-prompt v g)'"$PS1"
    fi
  #+END_SRC

  Good thing I seldom use a shell.

* My Function Collection

  Load up my [[file:sh-functions.org][shared functions]]. These can be shared with Bash, Fish and
  Zshell.

  #+BEGIN_SRC shell
    if [ -f $HOME/.sh-funcs.sh ]
    then
        . $HOME/.sh-funcs.sh
    fi
  #+END_SRC

  Host-specific values, are stored in a separate profile.

  #+BEGIN_SRC shell
    if [ -x $HOME/.profile-local ]
    then
      . $HOME/.profile-local
    fi
  #+END_SRC

* Technical Gunk

  Anything else that is interesting, will be set up in more
  either more shell-specific files, or in [[file:sh-functions.org][Shell Functions]] file.
  The following are the tangled settings. Type: =C-c C-v t=
  to create the script file.

#+DESCRIPTION: Global environment variables for all shells
#+PROPERTY: header-args:shell :tangle ~/.profile :shebang #!/bin/sh :comments org
