#!/bin/sh

sudo apt-get install -y zsh
sudo apt-get install -y tmux
sudo apt-get install -y emacs24-nox
sudo apt-get install -y source-highlight

emacs -Q --batch \
    --eval "(progn
     (require 'package)
     (setq package-archives '((\"org\"      . \"http://orgmode.org/elpa/\")
                             (\"gnu\"       . \"http://elpa.gnu.org/packages/\")
                             (\"melpa\"     . \"http://melpa.milkbox.net/packages/\")
                             (\"tromey\"    . \"http://tromey.com/elpa/\")
                             (\"marmalade\" . \"http://marmalade-repo.org/packages/\")))
    (package-initialize)
    (when (not package-archive-contents)
      (package-refresh-contents))

    (package-install 'emamux))"
